name: Docker Image CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build and Push C++ Docker image
        with:
          image: indusninja/cpp
          registry: docker.io
          dockerfile: Dockerfile.cpp.ci
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build and Push OpenGL Docker image
        with:
          image: indusninja/opengl
          registry: docker.io
          dockerfile: Dockerfile.opengl.ci
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build and Push Jekyll Docker image
        with:
          image: indusninja/jekyll
          registry: docker.io
          dockerfile: Dockerfile.jekyll.ci
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
